services:
  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8000:8000" # Mapare porturi între gazdă și container
    volumes:
      - ./flask:/app # Mapare director pentru dezvoltare
    environment:
      - FLASK_ENV=development # Activează modul de dezvoltare pentru Flask